extra:
  search:
    language: 'en, pt'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences

nav:
- Introdução: index.md
- LEIAME: LEIAME.md
- Aula 1 (2019-04-03): aula1.md
- Aula 2 (2019-04-05): aula2.md
- Aula 3 (2019-04-10): aula3.md
- Aula 4 (2019-04-12): aula4.md
- Aula 5 (2019-04-24): aula5.md
- Aula 6 (2019-04-26): aula6.md
- Aula 7 (2019-05-03): aula7.md
- Aula 8 (2019-05-08): aula8.md
- Aula 9 (2019-05-10): aula9.md
- Aula 10 (2019-05-17): aula10.md
- Aula 11 (2019-05-22): aula11.md
- Aula 12 (2019-05-24): aula12.md
- Aula 13 (2019-05-29): aula13.md
- Aula 14 (2019-05-31): aula14.md
- Aula 15 (2019-06-05): aula15.md
- Aula 16 (2019-06-07): aula16.md
- Aula 17 (2019-06-19): aula17.md
- Exercícios 1: exercicios1.md
- Exercícios 2: exercicios2.md
- Exercícios 3: exercicios3.md
- Exercícios 4: exercicios4.md
- Exercícios 5: exercicios5.md
- Trabalho 1: trabalho1.md
- FOR: for.md

plugins:
  - search

site_name: Estrutura de dados
site_description: Disciplina de estrutura de dados
site_author: Allainclair Flausino dos Santos
site_url: https://allainclair.github.io/disc-estrutura-dados

theme:
  language: pt
  name: material
