extra:
  search:
    language: 'en, pt'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences

nav:
- Introdução: index.md
- LEIAME: LEIAME.md
- Aula 1 (2019-04-03): aula1.md
- Aula 2 (2019-04-05): aula2.md
- Aula 3 (2019-04-10): aula3.md
- Aula 4 (2019-04-12): aula4.md
- Aula 5 (2019-04-24): aula5.md
- Exercícios 1: exercicios1.md
- Exercícios 2: exercicios2.md
- FOR: for.md

plugins:
  - search

site_name: Estrutura de dados
site_description: Disciplina de estrutura de dados
site_author: Allainclair Flausino dos Santos
site_url: https://allainclair.github.io/disc-estrutura-dados

theme:
  language: pt
  name: material
