extra:
  search:
    language: 'en, pt'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences

nav:
- Introdução: index.md
- LEIAME: LEIAME.md
- Aula 1 (2019-04-03): aula1.md
- Aula 2 (2019-04-05): aula2.md

plugins:
  - search
  - pdf-export

site_name: Estrutura de dados
site_description: Disciplina de estrutura de dados
site_author: Allainclair Flausino dos Santos
site_url: https://allainclair.github.io/disc-estrutura-dados

theme:
  language: pt
  name: material